apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: uks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uks
  template:
    metadata:
      labels:
        app: uks
    spec:
      containers:
      - name: uks
        image: gituks/uks-git-2019:second
        ports:
        - containerPort: 80
