# Generated by Django 2.1.7 on 2019-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_git', '0002_auto_20190326_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_value', models.CharField(max_length=500)),
                ('new_value', models.CharField(max_length=500)),
                ('attr_name', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('create', 'Create'), ('change', 'Change')], max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tasks',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
    ]
