# Generated by Django 2.1.7 on 2019-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_git', '0003_auto_20190326_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='history_item_type',
            field=models.OneToOneField(default=1, on_delete=models.SET(None), to='my_git.HistoryItemType'),
        ),
    ]
