# Generated by Django 2.1.7 on 2019-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_git', '0004_historyitem_history_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='history_item_type',
        ),
        migrations.AddField(
            model_name='historyitem',
            name='mode',
            field=models.CharField(choices=[('create', 'create'), ('change', 'change')], default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='HistoryItemType',
        ),
    ]
