# Generated by Django 2.1.7 on 2019-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_git', '0005_auto_20190326_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='mode',
            field=models.CharField(choices=[('create', 'create'), ('change', 'change')], default='create', max_length=6),
        ),
    ]
